=== analogdevicesinc/linux/drivers/gpu/drm/msm/registers/rules-fd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nouveau.freedesktop.org/"
	xmlns:rng="http://nouveau.freedesktop.org/"
	elementFormDefault="qualified">

	<annotation>
		<documentation>
			An updated version of the old rules.xml file from the
			RivaTV project. Specifications by Pekka Paalanen,
			preliminary attempt by KoalaBR,
			first working version by Jakob Bornecrantz.
			For specifications, see the file rules-ng-format.txt
			in Nouveau CVS module 'rules-ng'.
		</documentation>
		<documentation>Version 0.1</documentation>
	</annotation>


	<!-- Elements -->

	<element name="database"       type="rng:databaseType" />
	<element name="import"         type="rng:importType" />
	<element name="copyright"      type="rng:copyrightType" />
	<element name="domain"         type="rng:domainType" />
	<element name="array"          type="rng:arrayType" />
	<element name="stripe"         type="rng:stripeType" />
	<element name="reg64"          type="rng:registerType" />
	<element name="reg32"          type="rng:registerType" />
	<element name="bitset"         type="rng:bitsetType" />
	<element name="bitfield"       type="rng:bitfieldType" />
	<element name="enum"           type="rng:enumType" />
	<element name="value"          type="rng:valueType" />

	<!-- Copyright elements -->
	<element name="author"         type="rng:authorType" />
	<element name="nick"           type="rng:nickType" />
	<element name="license"        type="rng:docType" />

	<!-- Documentation elements -->
	
	<!-- FIXME: allowed only one  per parent element -->
	<element name="brief" type="rng:briefType" />
	
	<element name="doc"  type="rng:docType" />
	<element name="b"    type="rng:textformatType" />
	<element name="i"    type="rng:textformatType" />
	<element name="u"    type="rng:textformatType" />
	<element name="code" type="rng:textcodeType" />
	<element name="ul"   type="rng:listType" />
	<element name="ol"   type="rng:listType" />
	<element name="li"   type="rng:listitemType" />

	<!-- Copyright element types -->

	<complexType name="authorType" mixed="true">
		<annotation>
			<documentation>
				register database author
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="rng:nick" />
		</choice>
		<attribute name="name" type="string" use="required" />
		<attribute name="email" type="string" use="required" />
	</complexType>

	<complexType name="nickType">
		<annotation>
			<documentation>nickType</documentation>
		</annotation>
		<attribute name="name" type="string" use="required" />
	</complexType>

	<!-- Database element types -->

	<complexType name="databaseType">
		<annotation>
			<documentation>databaseType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
		</choice>
	</complexType>

	<complexType name="importType">
		<annotation>
			<documentation>importType</documentation>
		</annotation>
		<attribute name="file" type="string" use="required" />
	</complexType>

	<complexType name="copyrightType">
		<annotation>
			<documentation>copyrightType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
			<element ref="rng:author" />
			<element ref="rng:license" />
		</choice>
		<attribute name="year" type="nonNegativeInteger" use="optional" />
	</complexType>

	<complexType name="domainType">
		<annotation>
			<documentation>domainType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
			<group ref="rng:regarrayGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="prefix" type="NMTOKENS" use="optional" />
		<attribute name="width" type="rng:DomainWidth" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
	</complexType>

	<complexType name="arrayType">
		<annotation>
			<documentation>arrayType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
			<group ref="rng:regarrayGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="optional" />
		<attribute name="offset" type="rng:HexOrNumber" use="optional" />
		<attribute name="offsets" type="string" use="optional"/>
		<attribute name="doffsets" type="string" use="optional"/>
		<attribute name="index" type="NMTOKENS" use="optional"/>
		<attribute name="stride" type="rng:HexOrNumber" use="required" />
		<attribute name="length" type="rng:HexOrNumber" use="required" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
		<attribute name="usage" type="string" use="optional" />
	</complexType>

	<complexType name="stripeType">
		<annotation>
			<documentation>stripeType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
			<group ref="rng:regarrayGroup" minOccurs="0" />
		</choice>
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
		<attribute name="prefix" type="NMTOKENS" use="optional" />
	</complexType>

	<complexType name="registerType">
		<annotation>
			<documentation>
				registerType used by reg32, reg64
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
			<element ref="rng:value" />
			<element ref="rng:bitfield" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="offset" type="rng:HexOrNumber" use="required" />
		<attribute name="type" type="NMTOKENS" use="optional" />
		<attribute name="shr" type="nonNegativeInteger" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
		<attribute name="stride" type="rng:HexOrNumber" use="optional" />
		<attribute name="length" type="rng:HexOrNumber" use="optional" />
		<attribute name="high" type="nonNegativeInteger" use="optional" />
		<attribute name="low" type="nonNegativeInteger" use="optional" />
		<attribute name="pos" type="nonNegativeInteger" use="optional" />
		<attribute name="align" type="nonNegativeInteger" use="optional" />
		<attribute name="radix" type="nonNegativeInteger" use="optional" />
		<attribute name="usage" type="string" use="optional" />
	</complexType>

	<complexType name="bitsetType">
		<annotation>
			<documentation>bitsetType</documentation>
		</annotation>
		<choice maxOccurs="unbounded">
			<element ref="rng:bitfield" />
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="inline" type="rng:Boolean" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
	</complexType>

	<complexType name="bitfieldType">
		<annotation>
			<documentation>bitfieldType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="rng:value" maxOccurs="unbounded" />
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="high" type="nonNegativeInteger" use="optional" />
		<attribute name="low" type="nonNegativeInteger" use="optional" />
		<attribute name="pos" type="nonNegativeInteger" use="optional" />
		<attribute name="radix" type="nonNegativeInteger" use="optional" />
		<attribute name="type" type="NMTOKENS" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
		<attribute name="addvariant" type="rng:Boolean" use="optional" />
		<attribute name="shr" type="nonNegativeInteger" use="optional" />
	</complexType>

	<complexType name="enumType">
		<annotation>
			<documentation>enumType</documentation>
		</annotation>
		<choice maxOccurs="unbounded">
			<element ref="rng:value" />
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="bare" type="rng:Boolean" use="optional" />
		<attribute name="prefix" type="NMTOKENS" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
	</complexType>

	<complexType name="valueType">
		<annotation>
			<documentation>valueType</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:docGroup" />
			<group ref="rng:topGroup" />
		</choice>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="varset" type="NMTOKEN" use="optional" />
		<attribute name="variants" type="string" use="optional" />
	</complexType>

	<!-- Documentation element types -->

	<complexType name="briefType">
		<annotation>
			<documentation>
				brief documentation, no markup
			</documentation>
		</annotation>
		<simpleContent>
			<extension base="string" />
		</simpleContent>
	</complexType>
	
	<complexType name="docType" mixed="true">
		<annotation>
			<documentation>
				root element of documentation sub-tree
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:textformatGroup" />
			<group ref="rng:listGroup" />
			<element ref="rng:code" />
		</choice>
	</complexType>
	
	<complexType name="textformatType" mixed="true">
		<annotation>
			<documentation>
				for bold, underline, italics
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:textformatGroup" />
		</choice>
	</complexType>
	
	<complexType name="textcodeType">
		<simpleContent>
			<extension base="string">
				<attribute name="title" type="string" />
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="listType">
		<annotation>
			<documentation>
				definition of a list, ordered or unordered
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="rng:li" />
		</choice>
	</complexType>
	
	<complexType name="listitemType" mixed="true">
		<annotation>
			<documentation>
				items of a list
			</documentation>
		</annotation>
		<choice minOccurs="0" maxOccurs="unbounded">
			<group ref="rng:textformatGroup" />
			<group ref="rng:listGroup" />
			<element ref="rng:code" />
		</choice>
	</complexType>



	<!-- Attribute value types -->

	<simpleType name="Hexadecimal">
		<restriction base="string">
			<pattern value="0x[0-9a-f]+" />
			<pattern value="0x[0-9A-F]+" />
			<pattern value="[0-9]" />
		</restriction>
	</simpleType>

	<simpleType name="HexOrNumber">
		<annotation>
			<documentation>HexOrNumber</documentation>
		</annotation>
		<union memberTypes="rng:Hexadecimal nonNegativeInteger" />
	</simpleType>

	<simpleType name="Boolean">
		<restriction base="string">
			<enumeration value="true" />
			<enumeration value="1" />
			<enumeration value="yes" />
			<enumeration value="false" />
			<enumeration value="0" />
			<enumeration value="no" />
		</restriction>
	</simpleType>

	<simpleType name="DomainWidth">
		<annotation>
			<documentation>DomainWidth</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="32" />
		</restriction>
	</simpleType>



	<!-- Element groups -->

	<group name="topGroup">
		<choice>
			<element ref="rng:copyright" />
			<element ref="rng:domain" />
			<element ref="rng:enum" />
			<element ref="rng:bitset" />
			<element ref="rng:import" />
		</choice>
	</group>
	
	<group name="regarrayGroup">
		<choice>
			<element ref="rng:reg64" />
			<element ref="rng:reg32" />
			<element ref="rng:array" />
			<element ref="rng:stripe" />
		</choice>
	</group>
	
	<group name="docGroup">
		<choice>
			<element ref="rng:brief" />
			<element ref="rng:doc" />
		</choice>
	</group>
	
	<group name="textformatGroup">
		<choice>
			<element ref="rng:b" />
			<element ref="rng:i" />
			<element ref="rng:u" />
		</choice>
	</group>
	
	<group name="listGroup">
		<choice>
			<element ref="rng:ul" />
			<element ref="rng:ol" />
		</choice>
	</group>

</schema>

=== analogdevicesinc/linux/drivers/gpu/drm/msm/registers/display/dsi_phy_10nm.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://nouveau.freedesktop.org/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://gitlab.freedesktop.org/freedreno/ rules-fd.xsd">
<import file="freedreno_copyright.xml"/>

<domain name="DSI_10nm_PHY_CMN" width="32">
	<reg32 offset="0x00000" name="REVISION_ID0"/>
	<reg32 offset="0x00004" name="REVISION_ID1"/>
	<reg32 offset="0x00008" name="REVISION_ID2"/>
	<reg32 offset="0x0000c" name="REVISION_ID3"/>
	<reg32 offset="0x00010" name="CLK_CFG0"/>
	<reg32 offset="0x00014" name="CLK_CFG1"/>
	<reg32 offset="0x00018" name="GLBL_CTRL"/>
	<reg32 offset="0x0001c" name="RBUF_CTRL"/>
	<reg32 offset="0x00020" name="VREG_CTRL"/>
	<reg32 offset="0x00024" name="CTRL_0"/>
	<reg32 offset="0x00028" name="CTRL_1"/>
	<reg32 offset="0x0002c" name="CTRL_2"/>
	<reg32 offset="0x00030" name="LANE_CFG0"/>
	<reg32 offset="0x00034" name="LANE_CFG1"/>
	<reg32 offset="0x00038" name="PLL_CNTRL"/>
	<reg32 offset="0x00098" name="LANE_CTRL0"/>
	<reg32 offset="0x0009c" name="LANE_CTRL1"/>
	<reg32 offset="0x000a0" name="LANE_CTRL2"/>
	<reg32 offset="0x000a4" name="LANE_CTRL3"/>
	<reg32 offset="0x000a8" name="LANE_CTRL4"/>
	<reg32 offset="0x000ac" name="TIMING_CTRL_0"/>
	<reg32 offset="0x000b0" name="TIMING_CTRL_1"/>
	<reg32 offset="0x000b4" name="TIMING_CTRL_2"/>
	<reg32 offset="0x000b8" name="TIMING_CTRL_3"/>
	<reg32 offset="0x000bc" name="TIMING_CTRL_4"/>
	<reg32 offset="0x000c0" name="TIMING_CTRL_5"/>
	<reg32 offset="0x000c4" name="TIMING_CTRL_6"/>
	<reg32 offset="0x000c8" name="TIMING_CTRL_7"/>
	<reg32 offset="0x000cc" name="TIMING_CTRL_8"/>
	<reg32 offset="0x000d0" name="TIMING_CTRL_9"/>
	<reg32 offset="0x000d4" name="TIMING_CTRL_10"/>
	<reg32 offset="0x000d8" name="TIMING_CTRL_11"/>
	<reg32 offset="0x000ec" name="PHY_STATUS"/>
	<reg32 offset="0x000f4" name="LANE_STATUS0"/>
	<reg32 offset="0x000f8" name="LANE_STATUS1"/>
</domain>

<domain name="DSI_10nm_PHY" width="32">
	<array offset="0x00000" name="LN" length="5" stride="0x80">
		<reg32 offset="0x00" name="CFG0"/>
		<reg32 offset="0x04" name="CFG1"/>
		<reg32 offset="0x08" name="CFG2"/>
		<reg32 offset="0x0c" name="CFG3"/>
		<reg32 offset="0x10" name="TEST_DATAPATH"/>
		<reg32 offset="0x14" name="PIN_SWAP"/>
		<reg32 offset="0x18" name="HSTX_STR_CTRL"/>
		<reg32 offset="0x1c" name="OFFSET_TOP_CTRL"/>
		<reg32 offset="0x20" name="OFFSET_BOT_CTRL"/>
		<reg32 offset="0x24" name="LPTX_STR_CTRL"/>
		<reg32 offset="0x28" name="LPRX_CTRL"/>
		<reg32 offset="0x2c" name="TX_DCTRL"/>
	</array>
</domain>

<domain name="DSI_10nm_PHY_PLL" width="32">
	<reg32 offset="0x0000" name="ANALOG_CONTROLS_ONE"/>
	<reg32 offset="0x0004" name="ANALOG_CONTROLS_TWO"/>
	<reg32 offset="0x0010" name="ANALOG_CONTROLS_THREE"/>
	<reg32 offset="0x001c" name="DSM_DIVIDER"/>
	<reg32 offset="0x0020" name="FEEDBACK_DIVIDER"/>
	<reg32 offset="0x0024" name="SYSTEM_MUXES"/>
	<reg32 offset="0x002c" name="CMODE"/>
	<reg32 offset="0x0030" name="CALIBRATION_SETTINGS"/>
	<reg32 offset="0x0054" name="BAND_SEL_CAL_SETTINGS_THREE"/>
	<reg32 offset="0x0064" name="FREQ_DETECT_SETTINGS_ONE"/>
	<reg32 offset="0x007c" name="PFILT"/>
	<reg32 offset="0x0080" name="IFILT"/>
	<reg32 offset="0x0094" name="OUTDIV"/>
	<reg32 offset="0x00a4" name="CORE_OVERRIDE"/>
	<reg32 offset="0x00a8" name="CORE_INPUT_OVERRIDE"/>
	<reg32 offset="0x00b4" name="PLL_DIGITAL_TIMERS_TWO"/>
	<reg32 offset="0x00cc" name="DECIMAL_DIV_START_1"/>
	<reg32 offset="0x00d0" name="FRAC_DIV_START_LOW_1"/>
	<reg32 offset="0x00d4" name="FRAC_DIV_START_MID_1"/>
	<reg32 offset="0x00d8" name="FRAC_DIV_START_HIGH_1"/>
	<reg32 offset="0x010c" name="SSC_STEPSIZE_LOW_1"/>
	<reg32 offset="0x0110" name="SSC_STEPSIZE_HIGH_1"/>
	<reg32 offset="0x0114" name="SSC_DIV_PER_LOW_1"/>
	<reg32 offset="0x0118" name="SSC_DIV_PER_HIGH_1"/>
	<reg32 offset="0x011c" name="SSC_DIV_ADJPER_LOW_1"/>
	<reg32 offset="0x0120" name="SSC_DIV_ADJPER_HIGH_1"/>
	<reg32 offset="0x013c" name="SSC_CONTROL"/>
	<reg32 offset="0x0140" name="PLL_OUTDIV_RATE"/>
	<reg32 offset="0x0144" name="PLL_LOCKDET_RATE_1"/>
	<reg32 offset="0x014c" name="PLL_PROP_GAIN_RATE_1"/>
	<reg32 offset="0x0154" name="PLL_BAND_SET_RATE_1"/>
	<reg32 offset="0x015c" name="PLL_INT_GAIN_IFILT_BAND_1"/>
	<reg32 offset="0x0164" name="PLL_FL_INT_GAIN_PFILT_BAND_1"/>
	<reg32 offset="0x0180" name="PLL_LOCK_OVERRIDE"/>
	<reg32 offset="0x0184" name="PLL_LOCK_DELAY"/>
	<reg32 offset="0x018c" name="CLOCK_INVERTERS"/>
	<reg32 offset="0x01a0" name="COMMON_STATUS_ONE"/>
</domain>

</database>

=== analogdevicesinc/linux/drivers/gpu/drm/msm/registers/display/dsi_phy_28nm.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://nouveau.freedesktop.org/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://gitlab.freedesktop.org/freedreno/ rules-fd.xsd">
<import file="freedreno_copyright.xml"/>

<domain name="DSI_28nm_PHY" width="32">
	<array offset="0x00000" name="LN" length="4" stride="0x40">
		<reg32 offset="0x00" name="CFG_0"/>
		<reg32 offset="0x04" name="CFG_1"/>
		<reg32 offset="0x08" name="CFG_2"/>
		<reg32 offset="0x0c" name="CFG_3"/>
		<reg32 offset="0x10" name="CFG_4"/>
		<reg32 offset="0x14" name="TEST_DATAPATH"/>
		<reg32 offset="0x18" name="DEBUG_SEL"/>
		<reg32 offset="0x1c" name="TEST_STR_0"/>
		<reg32 offset="0x20" name="TEST_STR_1"/>
	</array>

	<reg32 offset="0x00100" name="LNCK_CFG_0"/>
	<reg32 offset="0x00104" name="LNCK_CFG_1"/>
	<reg32 offset="0x00108" name="LNCK_CFG_2"/>
	<reg32 offset="0x0010c" name="LNCK_CFG_3"/>
	<reg32 offset="0x00110" name="LNCK_CFG_4"/>
	<reg32 offset="0x00114" name="LNCK_TEST_DATAPATH"/>
	<reg32 offset="0x00118" name="LNCK_DEBUG_SEL"/>
	<reg32 offset="0x0011c" name="LNCK_TEST_STR0"/>
	<reg32 offset="0x00120" name="LNCK_TEST_STR1"/>

	<reg32 offset="0x00140" name="TIMING_CTRL_0">
		<bitfield name="CLK_ZERO" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00144" name="TIMING_CTRL_1">
		<bitfield name="CLK_TRAIL" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00148" name="TIMING_CTRL_2">
		<bitfield name="CLK_PREPARE" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x0014c" name="TIMING_CTRL_3">
		<bitfield name="CLK_ZERO_8" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x00150" name="TIMING_CTRL_4">
		<bitfield name="HS_EXIT" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00154" name="TIMING_CTRL_5">
		<bitfield name="HS_ZERO" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00158" name="TIMING_CTRL_6">
		<bitfield name="HS_PREPARE" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x0015c" name="TIMING_CTRL_7">
		<bitfield name="HS_TRAIL" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00160" name="TIMING_CTRL_8">
		<bitfield name="HS_RQST" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00164" name="TIMING_CTRL_9">
		<bitfield name="TA_GO" low="0" high="2" type="uint"/>
		<bitfield name="TA_SURE" low="4" high="6" type="uint"/>
	</reg32>
	<reg32 offset="0x00168" name="TIMING_CTRL_10">
		<bitfield name="TA_GET" low="0" high="2" type="uint"/>
	</reg32>
	<reg32 offset="0x0016c" name="TIMING_CTRL_11">
		<bitfield name="TRIG3_CMD" low="0" high="7" type="uint"/>
	</reg32>

	<reg32 offset="0x00170" name="CTRL_0"/>
	<reg32 offset="0x00174" name="CTRL_1"/>
	<reg32 offset="0x00178" name="CTRL_2"/>
	<reg32 offset="0x0017c" name="CTRL_3"/>
	<reg32 offset="0x00180" name="CTRL_4"/>

	<reg32 offset="0x00184" name="STRENGTH_0"/>
	<reg32 offset="0x00188" name="STRENGTH_1"/>

	<reg32 offset="0x001b4" name="BIST_CTRL_0"/>
	<reg32 offset="0x001b8" name="BIST_CTRL_1"/>
	<reg32 offset="0x001bc" name="BIST_CTRL_2"/>
	<reg32 offset="0x001c0" name="BIST_CTRL_3"/>
	<reg32 offset="0x001c4" name="BIST_CTRL_4"/>
	<reg32 offset="0x001c8" name="BIST_CTRL_5"/>

	<reg32 offset="0x001d4" name="GLBL_TEST_CTRL">
		<bitfield name="BITCLK_HS_SEL" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x001dc" name="LDO_CNTRL"/>
</domain>

<domain name="DSI_28nm_PHY_REGULATOR" width="32">
	<reg32 offset="0x00000" name="CTRL_0"/>
	<reg32 offset="0x00004" name="CTRL_1"/>
	<reg32 offset="0x00008" name="CTRL_2"/>
	<reg32 offset="0x0000c" name="CTRL_3"/>
	<reg32 offset="0x00010" name="CTRL_4"/>
	<reg32 offset="0x00014" name="CTRL_5"/>
	<reg32 offset="0x00018" name="CAL_PWR_CFG"/>
</domain>

<domain name="DSI_28nm_PHY_PLL" width="32">
	<reg32 offset="0x00000" name="REFCLK_CFG">
		<bitfield name="DBLR" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x00004" name="POSTDIV1_CFG"/>
	<reg32 offset="0x00008" name="CHGPUMP_CFG"/>
	<reg32 offset="0x0000C" name="VCOLPF_CFG"/>
	<reg32 offset="0x00010" name="VREG_CFG">
		<bitfield name="POSTDIV1_BYPASS_B" pos="1" type="boolean"/>
	</reg32>
	<reg32 offset="0x00014" name="PWRGEN_CFG"/>
	<reg32 offset="0x00018" name="DMUX_CFG"/>
	<reg32 offset="0x0001C" name="AMUX_CFG"/>
	<reg32 offset="0x00020" name="GLB_CFG">
		<bitfield name="PLL_PWRDN_B" pos="0" type="boolean"/>
		<bitfield name="PLL_LDO_PWRDN_B" pos="1" type="boolean"/>
		<bitfield name="PLL_PWRGEN_PWRDN_B" pos="2" type="boolean"/>
		<bitfield name="PLL_ENABLE" pos="3" type="boolean"/>
	</reg32>
	<reg32 offset="0x00024" name="POSTDIV2_CFG"/>
	<reg32 offset="0x00028" name="POSTDIV3_CFG"/>
	<reg32 offset="0x0002C" name="LPFR_CFG"/>
	<reg32 offset="0x00030" name="LPFC1_CFG"/>
	<reg32 offset="0x00034" name="LPFC2_CFG"/>
	<reg32 offset="0x00038" name="SDM_CFG0">
		<bitfield name="BYP_DIV" low="0" high="5" type="uint"/>
		<bitfield name="BYP" pos="6" type="boolean"/>
	</reg32>
	<reg32 offset="0x0003C" name="SDM_CFG1">
		<bitfield name="DC_OFFSET" low="0" high="5" type="uint"/>
		<bitfield name="DITHER_EN" pos="6" type="uint"/>
	</reg32>
	<reg32 offset="0x00040" name="SDM_CFG2">
		<bitfield name="FREQ_SEED_7_0" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00044" name="SDM_CFG3">
		<bitfield name="FREQ_SEED_15_8" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00048" name="SDM_CFG4"/>
	<reg32 offset="0x0004C" name="SSC_CFG0"/>
	<reg32 offset="0x00050" name="SSC_CFG1"/>
	<reg32 offset="0x00054" name="SSC_CFG2"/>
	<reg32 offset="0x00058" name="SSC_CFG3"/>
	<reg32 offset="0x0005C" name="LKDET_CFG0"/>
	<reg32 offset="0x00060" name="LKDET_CFG1"/>
	<reg32 offset="0x00064" name="LKDET_CFG2"/>
	<reg32 offset="0x00068" name="TEST_CFG">
		<bitfield name="PLL_SW_RESET" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x0006C" name="CAL_CFG0"/>
	<reg32 offset="0x00070" name="CAL_CFG1"/>
	<reg32 offset="0x00074" name="CAL_CFG2"/>
	<reg32 offset="0x00078" name="CAL_CFG3"/>
	<reg32 offset="0x0007C" name="CAL_CFG4"/>
	<reg32 offset="0x00080" name="CAL_CFG5"/>
	<reg32 offset="0x00084" name="CAL_CFG6"/>
	<reg32 offset="0x00088" name="CAL_CFG7"/>
	<reg32 offset="0x0008C" name="CAL_CFG8"/>
	<reg32 offset="0x00090" name="CAL_CFG9"/>
	<reg32 offset="0x00094" name="CAL_CFG10"/>
	<reg32 offset="0x00098" name="CAL_CFG11"/>
	<reg32 offset="0x0009C" name="EFUSE_CFG"/>
	<reg32 offset="0x000A0" name="DEBUG_BUS_SEL"/>
	<reg32 offset="0x000A4" name="CTRL_42"/>
	<reg32 offset="0x000A8" name="CTRL_43"/>
	<reg32 offset="0x000AC" name="CTRL_44"/>
	<reg32 offset="0x000B0" name="CTRL_45"/>
	<reg32 offset="0x000B4" name="CTRL_46"/>
	<reg32 offset="0x000B8" name="CTRL_47"/>
	<reg32 offset="0x000BC" name="CTRL_48"/>
	<reg32 offset="0x000C0" name="STATUS">
		<bitfield name="PLL_RDY" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x000C4" name="DEBUG_BUS0"/>
	<reg32 offset="0x000C8" name="DEBUG_BUS1"/>
	<reg32 offset="0x000CC" name="DEBUG_BUS2"/>
	<reg32 offset="0x000D0" name="DEBUG_BUS3"/>
	<reg32 offset="0x000D4" name="CTRL_54"/>
</domain>

</database>

=== analogdevicesinc/linux/drivers/gpu/drm/msm/registers/display/dsi_phy_28nm_8960.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://nouveau.freedesktop.org/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://gitlab.freedesktop.org/freedreno/ rules-fd.xsd">
<import file="freedreno_copyright.xml"/>

<domain name="DSI_28nm_8960_PHY" width="32">

	<array offset="0x00000" name="LN" length="4" stride="0x40">
		<reg32 offset="0x00" name="CFG_0"/>
		<reg32 offset="0x04" name="CFG_1"/>
		<reg32 offset="0x08" name="CFG_2"/>
		<reg32 offset="0x0c" name="TEST_DATAPATH"/>
		<reg32 offset="0x14" name="TEST_STR_0"/>
		<reg32 offset="0x18" name="TEST_STR_1"/>
	</array>

	<reg32 offset="0x00100" name="LNCK_CFG_0"/>
	<reg32 offset="0x00104" name="LNCK_CFG_1"/>
	<reg32 offset="0x00108" name="LNCK_CFG_2"/>

	<reg32 offset="0x0010c" name="LNCK_TEST_DATAPATH"/>
	<reg32 offset="0x00114" name="LNCK_TEST_STR0"/>
	<reg32 offset="0x00118" name="LNCK_TEST_STR1"/>

	<reg32 offset="0x00140" name="TIMING_CTRL_0">
		<bitfield name="CLK_ZERO" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00144" name="TIMING_CTRL_1">
		<bitfield name="CLK_TRAIL" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00148" name="TIMING_CTRL_2">
		<bitfield name="CLK_PREPARE" low="0" high="7" type="uint"/>
	</reg32>

	<reg32 offset="0x0014c" name="TIMING_CTRL_3"/>

	<reg32 offset="0x00150" name="TIMING_CTRL_4">
		<bitfield name="HS_EXIT" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00154" name="TIMING_CTRL_5">
		<bitfield name="HS_ZERO" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00158" name="TIMING_CTRL_6">
		<bitfield name="HS_PREPARE" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x0015c" name="TIMING_CTRL_7">
		<bitfield name="HS_TRAIL" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00160" name="TIMING_CTRL_8">
		<bitfield name="HS_RQST" low="0" high="7" type="uint"/>
	</reg32>
	<reg32 offset="0x00164" name="TIMING_CTRL_9">
		<bitfield name="TA_GO" low="0" high="2" type="uint"/>
		<bitfield name="TA_SURE" low="4" high="6" type="uint"/>
	</reg32>
	<reg32 offset="0x00168" name="TIMING_CTRL_10">
		<bitfield name="TA_GET" low="0" high="2" type="uint"/>
	</reg32>
	<reg32 offset="0x0016c" name="TIMING_CTRL_11">
		<bitfield name="TRIG3_CMD" low="0" high="7" type="uint"/>
	</reg32>

	<reg32 offset="0x00170" name="CTRL_0"/>
	<reg32 offset="0x00174" name="CTRL_1"/>
	<reg32 offset="0x00178" name="CTRL_2"/>
	<reg32 offset="0x0017c" name="CTRL_3"/>

	<reg32 offset="0x00180" name="STRENGTH_0"/>
	<reg32 offset="0x00184" name="STRENGTH_1"/>
	<reg32 offset="0x00188" name="STRENGTH_2"/>

	<reg32 offset="0x0018c" name="BIST_CTRL_0"/>
	<reg32 offset="0x00190" name="BIST_CTRL_1"/>
	<reg32 offset="0x00194" name="BIST_CTRL_2"/>
	<reg32 offset="0x00198" name="BIST_CTRL_3"/>
	<reg32 offset="0x0019c" name="BIST_CTRL_4"/>

	<reg32 offset="0x001b0" name="LDO_CTRL"/>
</domain>

<domain name="DSI_28nm_8960_PHY_MISC" width="32">
	<reg32 offset="0x00000" name="REGULATOR_CTRL_0"/>
	<reg32 offset="0x00004" name="REGULATOR_CTRL_1"/>
	<reg32 offset="0x00008" name="REGULATOR_CTRL_2"/>
	<reg32 offset="0x0000c" name="REGULATOR_CTRL_3"/>
	<reg32 offset="0x00010" name="REGULATOR_CTRL_4"/>
	<reg32 offset="0x00014" name="REGULATOR_CTRL_5"/>
	<reg32 offset="0x00018" name="REGULATOR_CAL_PWR_CFG"/>
	<reg32 offset="0x00028" name="CAL_HW_TRIGGER"/>
	<reg32 offset="0x0002c" name="CAL_SW_CFG_0"/>
	<reg32 offset="0x00030" name="CAL_SW_CFG_1"/>
	<reg32 offset="0x00034" name="CAL_SW_CFG_2"/>
	<reg32 offset="0x00038" name="CAL_HW_CFG_0"/>
	<reg32 offset="0x0003c" name="CAL_HW_CFG_1"/>
	<reg32 offset="0x00040" name="CAL_HW_CFG_2"/>
	<reg32 offset="0x00044" name="CAL_HW_CFG_3"/>
	<reg32 offset="0x00048" name="CAL_HW_CFG_4"/>
	<reg32 offset="0x00050" name="CAL_STATUS">
		<bitfield name="CAL_BUSY" pos="4" type="boolean"/>
	</reg32>
</domain>

<domain name="DSI_28nm_8960_PHY_PLL" width="32">
	<reg32 offset="0x00000" name="CTRL_0">
		<bitfield name="ENABLE" pos="0" type="boolean"/>
	</reg32>
	<reg32 offset="0x00004" name="CTRL_1"/>
	<reg32 offset="0x00008" name="CTRL_2"/>
	<reg32 offset="0x0000c" name="CTRL_3"/>
	<reg32 offset="0x00010" name="CTRL_4"/>
	<reg32 offset="0x00014" name="CTRL_5"/>
	<reg32 offset="0x00018" name="CTRL_6"/>
	<reg32 offset="0x0001c" name="CTRL_7"/>
	<reg32 offset="0x00020" name="CTRL_8"/>
	<reg32 offset="0x00024" name="CTRL_9"/>
	<reg32 offset="0x00028" name="CTRL_10"/>
	<reg32 offset="0x0002c" name="CTRL_11"/>
	<reg32 offset="0x00030" name="CTRL_12"/>
	<reg32 offset="0x00034" name="CTRL_13"/>
	<reg32 offset="0x00038" name="CTRL_14"/>
	<reg32 offset="0x0003c" name="CTRL_15"/>
	<reg32 offset="0x00040" name="CTRL_16"/>
	<reg32 offset="0x00044" name="CTRL_17"/>
	<reg32 offset="0x00048" name="CTRL_18"/>
	<reg32 offset="0x0004c" name="CTRL_19"/>
	<reg32 offset="0x00050" name="CTRL_20"/>

	<reg32 offset="0x00080" name="RDY">
		<bitfield name="PLL_RDY" pos="0" type="boolean"/>
	</reg32>
</domain>

</database>
